import { ModalDataT } from '@/shared/types';

export const initialModalData: ModalDataT = {
  isOpen: false,
  type: 'add',
  isRequested: false,
  fields: {
    gender: {
      type: 'select',
      required: true,
      label: 'Номер заказа',
      options: [],
      placeholder: 'Выбрать',
    },
    shop: {
      type: 'select',
      required: true,
      label: 'Магазин',
      options: [],
      placeholder: 'Выбрать',
    },
    buyer: {
      type: 'select',
      required: true,
      label: 'Покупатель',
      options: [],
      placeholder: 'Выбрать',
    },
    birth_date: {
      type: 'date',
      label: 'Дата  и время оформления заказа',
      placeholder: '00/00/1900',
    },
    pay_status: {
      type: 'select',
      required: true,
      label: 'Статус оплаты',
      options: [],
      placeholder: 'Выбрать',
    },
    order_status: {
      type: 'select',
      required: true,
      label: 'Статус товара',
      options: [],
      placeholder: 'Выбрать',
    },
    order_sum: {
      type: 'select',
      required: true,
      label: 'Сумма заказа',
      options: [],
      placeholder: 'Выбрать',
    },
    deivery_address: {
      type: 'select',
      required: true,
      label: 'Адрес доставки',
      options: [],
      placeholder: 'Выбрать',
    },
    iin: {
      type: 'number',
      label: 'ИНН',
      required: true,
      placeholder: '0',
    },
    manager: {
      type: 'select',
      required: true,
      label: 'Менеджер',
      options: [],
      placeholder: 'Выбрать',
    },
    email: {
      type: 'text',
      required: true,
      label: 'Почта',
    },
    phone: {
      type: 'number',
      label: 'Номер телефона',
      placeholder: '+0',
      required: true,
    },
    note: {
      type: 'select',
      required: true,
      label: 'Примечание',
      options: [],
      placeholder: 'Выбрать',
    },
  },
  values: {
    type: 2,
    first_name: '',
    last_name: '',
    gender: '',
    email: '',
    phone: '',
    birth_date: '',
    address: '',
    tags: '',
    iin: '',
    count_orders: '',
    orders: '',
    sum_orders: '',
    sub_whatsapp: '',
    sub_email: '',
    password: '',
  },
  validation: {
    error: {
      type: false,
      status: false,
      name: false,
      name_ru: false,
    },
    message: {
      type: '',
      status: '',
      name: '',
      name_ru: '',
    },
  },
};
