import { GridColDef } from '@mui/x-data-grid';
import { format } from 'date-fns';

export const columns: GridColDef[] = [
  {
    type: 'string',
    headerName: 'Дата',
    sortable: true,
    field: 'created_at',
    flex: 1,
    width: 60,
    valueFormatter: (value) => format(value, 'dd/MM/yyyy'),
  },
  {
    type: 'string',
    headerName: 'Тип',
    field: 'id',
    width: 70,
    sortable: true,
  },
  {
    type: 'string',
    headerName: 'Заказ',
    sortable: true,
    field: 'ss',
    width: 80,
  },
  {
    type: 'string',
    headerName: 'Клиент',
    sortable: true,
    field: 'first_name',
    flex: 1,
    width: 80,
    renderCell: ({ row }) => `${row.first_name} ${row.last_name}`,
  },
  {
    type: 'string',
    headerName: 'Отправитель',
    field: 'phone',
    flex: 1,
    sortable: true,
    width: 170,
  },
  {
    type: 'string',
    headerName: 'Получатель',
    field: 'phonsse',
    flex: 1,
    sortable: true,
    width: 50,
  },
  {
    type: 'string',
    headerName: 'Тема',
    field: 'email',
    flex: 1,
    sortable: true,
    width: 50,
  },
  {
    type: 'string',
    headerName: 'Статус входящих',
    sortable: true,
    field: 'iin',
    flex: 1,
    width: 50,
  },
  {
    type: 'string',
    headerName: 'Статус исходящих',
    sortable: true,
    field: 'iasdasdin',
    flex: 1,
    width: 50,
  },
  {
    type: 'string',
    headerName: 'Вид',
    sortable: true,
    field: 'iasdasdissn',
    flex: 1,
    width: 50,
  },
];
